lo:
  hostname: liveobjects.orange-business.com
  api-key:
  topic:
  keep-alive-interval-seconds: 30
  automatic-reconnect: true
  message-qos: 1
  mqtt-persistence-dir: ${basedir:.}/temp/
  connection-timeout: 30000

azure:
  evt-hub:
    name-space:
    evt-hub-name:
    sas-key-name: RootManageSharedAccessKey
    sas-key:
    thread-pool-size: 40
    task-queue-size: 150000
    connection-timeout: 5000
    throttling-delay: 5ms
    max-send-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, beans, counters